# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('telegram_id', models.IntegerField(db_index=True)),
                ('telegram_status', models.IntegerField(default=0)),
                ('wait_till', models.DateTimeField()),
                ('car_id', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
