# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpqw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(db_index=True)),
                ('prefix', models.CharField(default='ru', max_length=10)),
            ],
        ),
    ]
